### PR TITLE
Update the package deps

### PR DESCRIPTION
**Pull request by bbatsov**
I've also tweaked the package version to reflect reality. Might be good to call this 1.0 at some point, as I see it hasn't changed much in recent years.

### CODE REVIEW

**Comment by bbatsov** [comment]
I've cut a new Flycheck release, which should fix the CI issue. (see https://github.com/flycheck/flycheck/blob/master/CHANGES.rst#341-2024-02-18)

**Comment by borkdude** [comment]
Hi @bbatsov - thanks! Should we retrigger CI then?

**Comment by bbatsov** [comment]
I guess it will take a few hours for the new version to become available on MELPA, so we'll have to wait a bit first.

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
